### ISSUE TITLE
New upload can only be published after page refresh

### ISSUE THREAD

**Issue by slint** [zenodo/zenodo-rdm#998] opened 2024-09-26 08:31 UTC
To reproduce:

1. Install `invenio-rdm-records==12.2.1` (currently at 2024-09-26T10:33:22, the latest published)
2. Create a new upload
3. Fill in all the required fields for the form
4. The "Publish" button is still disabled
5. If you refresh the page, the "Publish" button becomes enabled and you can publish the record

---

The changes introduced in https://github.com/inveniosoftware/invenio-rdm-records/pull/1768, rely on the `can_publish` permission to determine if the "Publish" button is enabled.

When creating a new upload, the permission calculates to `can_publish: false`, since there is no record to run the permission check against. When refreshing the page the permission is re-calculated and the permission button becomes enabled.

**Comment by Samk13** [comment] 2024-09-26 08:52
This issue seems to be a duplicate of [2854](https://github.com/inveniosoftware/invenio-app-rdm/issues/2854)

**Closed** 2024-09-26 09:40 UTC
